// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthInput struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	RememberMe bool   `json:"rememberMe"`
}

type Travel struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CoverImage  string    `json:"coverImage"`
	CreatedAt   time.Time `json:"createdAt"`
	StartDate   time.Time `json:"startDate"`
	EndDate     time.Time `json:"endDate"`
	Location    string    `json:"location"`
	User        *User     `json:"user"`
	Soldout     bool      `json:"soldout"`
	Clients     []*User   `json:"clients"`
}

type User struct {
	ID            string    `json:"id"`
	Username      string    `json:"username"`
	Email         string    `json:"email"`
	Password      string    `json:"password"`
	AvatarImage   *string   `json:"avatarImage"`
	BookedTravels []*Travel `json:"bookedTravels"`
}
